<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="14.0.0" />
        <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\application\ZedLive.Application\ZedLive.Application.csproj" />
        <ProjectReference Include="..\..\infrastructure\ZedLive.Infrastructure\ZedLive.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
