// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZedLive.Infrastructure.Data.Context;

#nullable disable

namespace ZedLive.Infrastructure.Migrations
{
    [DbContext(typeof(ZedLiveContext))]
    [Migration("20260313011821_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZedLive.Domain.User.StatusUser", b =>
                {
                    b.Property<byte>("id")
                        .HasColumnType("smallint");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.ToTable("tb_status_user", "dbo");

                    b.HasData(
                        new
                        {
                            id = (byte)1,
                            value = "Online"
                        },
                        new
                        {
                            id = (byte)2,
                            value = "Offline"
                        },
                        new
                        {
                            id = (byte)3,
                            value = "Inactive"
                        });
                });

            modelBuilder.Entity("ZedLive.Domain.User.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<byte>("StatusUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status_user_id");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("StatusUserId")
                        .IsUnique();

                    b.HasIndex("StreamKey")
                        .IsUnique();

                    b.ToTable("tb_usuarios", "dbo");
                });

            modelBuilder.Entity("ZedLive.Domain.User.User", b =>
                {
                    b.HasOne("ZedLive.Domain.User.StatusUser", "StatusUser")
                        .WithOne()
                        .HasForeignKey("ZedLive.Domain.User.User", "StatusUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ZedLive.Domain.ValueObjects.EmailObject", "Email", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(266)
                                .HasColumnType("varchar")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("tb_usuarios", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ZedLive.Domain.ValueObjects.PasswordObject", "Password", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("password");

                            b1.HasKey("UserId");

                            b1.ToTable("tb_usuarios", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("StatusUser");
                });
#pragma warning restore 612, 618
        }
    }
}
