worker_connections auto;

events {
   work_process 1024; 
}

http{
    sendfile on;
    
    upstream api{
        server api1:9001;
        server api1:9002;
    }
    
    server {
        listen 9999;
        location / {
            proxy_pass http://api;
        }
    }
}